[2024-10-08 11:26:39,649: INFO/MainProcess] beat: Starting...
[2024-10-08 11:26:39,691: INFO/MainProcess] Scheduler: Sending due task create-events-daily (services_menage.tasks.service_checkin_task)
 
 -------------- celery@debian-hpelite v5.4.0 (opalescent)
--- ***** ----- 
-- ******* ---- Linux-5.10.0-32-amd64-x86_64-with-glibc2.31 2024-10-08 11:26:39
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         conciergerie:0x7f8ddf793f10
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . services_menage.tasks.faire_etat_des_lieu_appart
  . services_menage.tasks.service_checkin_task
  . services_menage.tasks.service_menage_task

[2024-10-08 11:26:39,982: INFO/MainProcess] Connected to redis://localhost:6379//
[2024-10-08 11:26:39,987: INFO/MainProcess] mingle: searching for neighbors
[2024-10-08 11:26:40,996: INFO/MainProcess] mingle: all alone
[2024-10-08 11:26:41,012: INFO/MainProcess] celery@debian-hpelite ready.
[2024-10-08 11:26:41,015: INFO/MainProcess] Task services_menage.tasks.service_checkin_task[8570a89c-d851-4e54-94b3-df6027348337] received
[2024-10-08 11:26:41,092: INFO/ForkPoolWorker-4] Task services_menage.tasks.service_checkin_task[8570a89c-d851-4e54-94b3-df6027348337] succeeded in 0.0759052299981704s: None
[I 241008 11:26:50 command:168] Visit me at http://0.0.0.0:5555
[I 241008 11:26:50 command:176] Broker: redis://localhost:6379//
[I 241008 11:26:50 command:177] Registered tasks: 
    ['celery.accumulate',
     'celery.backend_cleanup',
     'celery.chain',
     'celery.chord',
     'celery.chord_unlock',
     'celery.chunks',
     'celery.group',
     'celery.map',
     'celery.starmap',
     'services_menage.tasks.faire_etat_des_lieu_appart',
     'services_menage.tasks.service_checkin_task',
     'services_menage.tasks.service_menage_task']
[I 241008 11:26:50 mixins:228] Connected to redis://localhost:6379//
/home/django/Depots/www/Back-end/Django/envCeleryConciergerie/lib/python3.9/site-packages/celery/app/control.py:56: DuplicateNodenameWarning: Received multiple replies from node name: celery@debian-hpelite.
Please make sure you give each node a unique nodename using
the celery worker `-n` option.
  warnings.warn(DuplicateNodenameWarning(
[2024-10-08 11:26:55,539: INFO/MainProcess] Events of group {task} enabled by remote.
